<center>    
    <h1 id='matrix-decomposition-notebook-0' style='color:#7159c1; font-size:350%'>LU Decomposition</h1>
    <i style='font-size:125%'>Breaking Matrices into Blocks</i>
</center>

> **Topics**

```
- 🛡️ LU Decomposition
```

In [2]:
# ---- Imports ----
import numpy as np
from IPython.display import HTML

# ---- Constants ----
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-lu-decomposition' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🛡️ | LU Decomposition</h1>

`LU Decomposition` decomposes any square matrix $\mathbf{A}$ into two ones: $\mathbf{L}$ and $\mathbf{U}$:

$$
\mathbf{A} = \mathbf{L} \cdot \mathbf{U}
$$

where:

- **$\mathbf{A}$** - `Square Matrix`;

- **$\mathbf{L}$** - `Lower Triangular Matrix`;

- **$\mathbf{U}$** - `Upper Triangular Matrix`.

In order to explain this decomposition step-by-step, let's go to a hands-on exercise!!

Consider the matrix $\mathbf{A}$:

$$
\mathbf{A} = \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 2 & 1 \\
    2 & 3 & 1
\end{bmatrix}
$$

---

**- Step 1) Define matrix L as an Image Matrix and matrix U as a copy of matrix A:**

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 2 & 1 \\
    2 & 3 & 1
\end{bmatrix}
$$

---

- **Step 2) Given matrix U's first column, calculate the numbers multiplied by the first row that results to zero when `subtracted` by the second and third rows:**

$$
\mathbf{U}_\text{first column} = \begin{bmatrix}1 \\ 3 \\ 2\end{bmatrix}
$$

The first row is 1; so, in order to tranform the second row (3) to zero, we must multiply the first one by `3`; and, to transform the third row (2) to zero, we must multiply the first by `2`. Then:

$$
\begin{aligned}
\text{Second Row} = \text{Second Row} - \text{First Row} \cdot 3 = 3 - 1 \cdot 3 = 3 - 3 = 0 \\ \\
\text{Third Row} = \text{Third Row} - \text{First Row} \cdot 2 = 2 - 1 \cdot 2 = 2 - 2 = 0
\end{aligned}
$$

After that, we insert the numbers used in the multiplication into $\mathbf{L}$ matrix, each one in their respective column and row applied to transform the elements into zero in $\mathbf{U}$. Then, `3` goes in the first column, second row position in $\mathbf{L}$; and `2` goes in the first column, third row position. About $\mathbf{U}$, we replace the very same positions by `0`'s.

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    3 & 1 & 0 \\
    2 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    1 & 2 & 3 \\
    0 & 2 & 1 \\
    0 & 3 & 1
\end{bmatrix}
$$

Now, we must do the same process with the other columns, so we must multiply the first row by three and subtract the second row by the result, and multiply the first row by two and subtract the third row by the result!!

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    3 & 1 & 0 \\
    2 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    1 & 2 & 3   \\
    0 & -4 & -8 \\
    0 & -1 & -5
\end{bmatrix}
$$

---

**- Step 3) Repeat the same process using the second column:**

Now we just repeat the same process with all columns to finish the decomposition. For each column, we must use their respective index row.

For instance, when transforming the first column, we used the first row to multiply a number `n` and then subtract the other rows. Now for the second column, we use the second row; for the third column, we use the third row; and so on.

$$
\mathbf{U}_\text{second column} = \begin{bmatrix} 2 \\ -4 \\ -1 \end{bmatrix}
$$

The second row value is -4 and, in order to transform the third one to zero, we must multiply by `0.25`:

$$
\text{Third Row} = \text{Third Row} - \text{Second Row} \cdot 0.25 =  -1 - (-4 \cdot 0.25) = -1 - (-1) = -1 + 1 = 0
$$

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    3 & 1 & 0 \\
    2 & 0.25 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    1 & 2 & 3   \\
    0 & -4 & -8 \\
    0 & 0 & -5
\end{bmatrix}
$$

And now we do the same process to the third column, multiplying the second row by `0.25` and then subtracting the third row by the result:

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    3 & 1 & 0 \\
    2 & 0.25 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    1 & 2 & 3   \\
    0 & -4 & -8 \\
    0 & 0 & -3
\end{bmatrix}
$$

---

And done!! Our matrix $\mathbf{A}$ has just been decomposed into a `Lower Triangular Matrix` ($\mathbf{L}$) and an `Upper Triangular Matrix` ($\mathbf{U}$):

$$
\begin{array}
    \mathbf{A} = \mathbf{L} \cdot \mathbf{U} \\ \\
    \big\downarrow \\ \\
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 2 & 1 \\
        2 & 3 & 1
    \end{bmatrix} =
    \begin{bmatrix}
        1 & 0 & 0 \\
        3 & 1 & 0 \\
        2 & 0.25 & 1
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        1 & 2 & 3   \\
        0 & -4 & -8 \\
        0 & 0 & -3
    \end{bmatrix}
\end{array}
$$

In [3]:
# ---- LU Decomposition: Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/00-LUDecomposition.mp4', VIDEOS_WIDTH))

In [4]:
# ---- LU Decomposition ----
A = np.matrix([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
L = np.matrix([[1, 0, 0], [3, 1, 0], [2, 0.25, 1]])
U = np.matrix([[1, 2, 3], [0, -4, -8], [0, 0, -3]])
L_dot_U = L @ U

print(f'- Matrix A: {A}')
print('---')
print(f'- L * U: {L_dot_U}')
print('---')
print(f'- Are A and L * U equal? {np.allclose(A, L_dot_U)}')

- Matrix A: [[1 2 3]
 [3 2 1]
 [2 3 1]]
---
- L * U: [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]
---
- Are A and L * U equal? True


---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).