<center>    
    <h1 id='matrix-decomposition-notebook-1' style='color:#7159c1; font-size:350%'>PLU Decomposition</h1>
    <i style='font-size:125%'>Breaking Matrices into Blocks</i>
</center>

> **Topics**

```
- 🛡️ PLU Decomposition
```

In [1]:
# ---- Imports ----
import numpy as np
import scipy
from IPython.display import HTML

# ---- Constants ----
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-plu-decomposition' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🛡️ | PLU Decomposition</h1>

`PLU Decomposition` decomposes any square matrix $\mathbf{A}$ into three ones: $\mathbf{P}$, $\mathbf{L}$ and $\mathbf{U}$:

$$
\mathbf{A} = \mathbf{P} \cdot \mathbf{L} \cdot \mathbf{U}
$$

where:

- **$\mathbf{A}$** - `Square Matrix`;

- **$\mathbf{P}$** - `Permutation Matrix`;

- **$\mathbf{L}$** - `Lower Triangular Matrix`;

- **$\mathbf{U}$** - `Upper Triangular Matrix`.

In order to explain this decomposition step-by-step, let's go to a hands-on exercise!!

Consider the matrix $\mathbf{A}$:

$$
\mathbf{A} = \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 2 & 1 \\
    2 & 3 & 1
\end{bmatrix}
$$

---

**- Step 1) Rearrange the matrix $\mathbf{A}$ and create the matrix $\mathbf{P}:$**

We first rearrange the matrix $\mathbf{A}$ by finding the largest absolute value per column, but the last one.

Taking the first column into consideration, we can notice that `3` in the second row is the largest absolute value, so we swap the first and the second rows:

$$
\mathbf{A} = \begin{bmatrix}
    3 & 2 & 1 \\
    1 & 2 & 3 \\
    2 & 3 & 1
\end{bmatrix}
$$

Now, taking the second column, we can notice that `3` in the third row is the largest absolute value, so we swap the new second and the third rows:

$$
\mathbf{A} = \begin{bmatrix}
    3 & 2 & 1 \\
    2 & 3 & 1 \\
    1 & 2 & 3
\end{bmatrix}
$$

With $\mathbf{A}$ rearranged, we can now create $\mathbf{P}$ as an Image Matrix and adding all the permutations (rearrangements) we did so far.

For instance, consider $\mathbf{P}$ as:

$$
\mathbf{P} = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

Since we swapped the first and second rows, we do the same with it:

$$
\mathbf{P} = \begin{bmatrix}
    0 & 1 & 0 \\
    1 & 0 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

And, since we swapped the new second and the third rows, we do the same with it, but we must remember that the new second row was our previous first row, so, in this case and only for $\mathbf{P}$ matrix, we must swap the second row (new first row) and the third one:

$$
\mathbf{P} = \begin{bmatrix}
    0 & 0 & 1 \\
    1 & 0 & 0 \\
    0 & 1 & 0
\end{bmatrix}
$$

After all this, we have the following matrices so far:

$$
\mathbf{A} = \begin{bmatrix}
    3 & 2 & 1 \\
    2 & 3 & 1 \\
    1 & 2 & 3
\end{bmatrix}
\quad
\mathbf{P} = \begin{bmatrix}
    0 & 0 & 1 \\
    1 & 0 & 0 \\
    0 & 1 & 0
\end{bmatrix}
$$

---

**- Step 2) Define matrix $\mathbf{L}$ as an Image Matrix and matrix $\mathbf{U}$ as a copy of matrix $\mathbf{A}$:**

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    3 & 2 & 1 \\
    2 & 3 & 1 \\
    1 & 2 & 3
\end{bmatrix}
$$

---

**- Step 3) Given matrix U's first column, calculate the numbers multiplied by the first row that results to zero when `subtracted` by the second and third rows:**

$$
\mathbf{U}_\text{first column} = \begin{bmatrix} 3 \\ 2 \\ 1 \end{bmatrix}
$$

The first row is 3; so, in order to transform the second row (2) to zero, we must multiply the first one by `2/3`; and, to transform the third row (1) to zero, we must multiply the first by `1/3`. Then:

$$
\begin{aligned}
    \text{Second Row} = \text{Second Row} - \text{First Row} \cdot \frac{2}{3} = 2 - 3 \cdot \frac{2}{3} = 2 - 2 = 0 \\
    \text{Third Row} = \text{Third Row} - \text{First Row} \cdot \frac{1}{3} = 1 - 3 \cdot \frac{1}{3} = 1 - 1 = 0
\end{aligned}
$$

After that, we insert the numbers used in the multiplication into $\mathbf{L}$ matrix, each one in their respective column and row applied to transform the elements into zero in $\mathbf{U}$. Then, `2/3 (0.6667)` goes in the first column, second row position in $\mathbf{L}$; and `1/3 (0.3334)` goes in the first column, third row position. About $\mathbf{U}$, we replace the very same positions by `0`'s:

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    0.6667 & 1 & 0 \\
    0.3334 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    3 & 2 & 1 \\
    0 & 3 & 1 \\
    0 & 2 & 3
\end{bmatrix}
$$

Now, we must do the same process with the other columns, so we must multiply the first row by `2/3` and subtract the second row by the result; and multiply the first row by `1/3` and subtract the third row by the result!!

$$
\mathbf{L} = \begin{bmatrix}
    1 & 0 & 0 \\
    0.6667 & 1 & 0 \\
    0.3334 & 0 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    3 & 2 & 1 \\
    0 & 1.6667 & 0.3334 \\
    0 & 1.3334 & 2.6667
\end{bmatrix}
$$

---

**- Step 4) Repeat the same process using the second column:**

Now we just repeat the same process with all columns to finish the decomposition. For each column, we must use their respective index row.

For instance, when transforming the first column, we used the first row to multiply a number `n` and the subtract the other rows. Now, for the second column, we use the second row; for the third column, we use the third row; and so on.

$$
\mathbf{U}_\text{second column} = \begin{bmatrix} 2 \\ 1.6667 \\ 1.3334 \end{bmatrix}
$$

The second row value is 1.6667, in order to transform the third one to zero, we multiply by `0.80`:

$$
\text{Third Row} = \text{Third Row} - \text{Second Row} \cdot 0.80 = 1.3334 - 1.6667 \cdot 0.80 = 1.3334 - 1.3334 = 0
$$

$$
\mathbf{L} = \begin{bmatrix}
    1      & 0    & 0 \\
    0.6667 & 1    & 0 \\
    0.3334 & 0.80 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    3 & 2      & 1 \\
    0 & 1.6667 & 0.3334 \\
    0 & 0      & 2.6667
\end{bmatrix}
$$

And now we do the same process to the third column, multiplying the second row by `0.80` and then subtracting the third row by the result:

$$
\mathbf{L} = \begin{bmatrix}
    1      & 0    & 0 \\
    0.6667 & 1    & 0 \\
    0.3334 & 0.80 & 1
\end{bmatrix}
\quad
\mathbf{U} = \begin{bmatrix}
    3 & 2      & 1      \\
    0 & 1.6667 & 0.3334 \\
    0 & 0      & 2.40
\end{bmatrix}
$$

---

And done!! Our matrix $\mathbf{A}$ has just been decomposed into a `Permutation Matrix` ($\mathbf{P}$), a `Lower Triangular Matrix` ($\mathbf{L}$) and an `Upper Triangular Matrix` ($\mathbf{U}$):

$$
\begin{array}
    \mathbf{A} = \mathbf{P} \cdot \mathbf{L} \cdot \mathbf{U} \\ \\
    \big\downarrow \\ \\
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 2 & 1 \\
        2 & 3 & 1
    \end{bmatrix} =
    \begin{bmatrix}
        0 & 0 & 1 \\
        1 & 0 & 0 \\
        0 & 1 & 0
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
    1      & 0    & 0 \\
    0.6667 & 1    & 0 \\
    0.3334 & 0.80 & 1
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        3 & 2      & 1 \\
        0 & 1.6667 & 0.3334 \\
        0 & 0      & 2.6667
    \end{bmatrix}
\end{array}
$$

In [6]:
# ---- PLU Decomposition: Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/01-PLUDecomposition.mp4', VIDEOS_WIDTH))

In [5]:
# ---- PLU Decomposition ----
A = np.matrix([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
P, L, U = scipy.linalg.lu(A)
P_dot_L_dot_U = P @ L @ U

print(f'- Matrix A: {A}')
print('---')
print(f'- P * L * U: {P_dot_L_dot_U}')
print('---')
print(f'- Are A and P * L * U equal? {np.allclose(A, P_dot_L_dot_U)}')

- Matrix A: [[1 2 3]
 [3 2 1]
 [2 3 1]]
---
- P * L * U: [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]
---
- Are A and P * L * U? True


---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).