<center>    
    <h1 id='matrix-decomposition-notebook-2' style='color:#7159c1; font-size:350%'>QR Decomposition</h1>
    <i style='font-size:125%'>Breaking Matrices into Blocks</i>
</center>

> **Topics**

```
- 🛡️ QR Decomposition
```

In [1]:
# ---- Imports ----
import numpy as np
import scipy
from IPython.display import HTML

# ---- Constants ----
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-qr-decomposition' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🛡️ | QR Decomposition</h1>

`QR Decomposition` decomposes any matrix $\mathbf{A}$ into two ones: $\mathbf{Q}$ and $\mathbf{R}$:

$$
\mathbf{A} = \mathbf{Q} \cdot \mathbf{R}
$$

where:

- **$\mathbf{A}$** - `Any Matrix`;

- **$\mathbf{Q}$** - `Orthonormal Matrix`;

- **$\mathbf{R}$ (AKA $\mathbf{U}$)** - `Upper Triangular Matrix`.

In order to explain this decomposition step-by-step, let's go to a hands-on exercise!!

In [2]:
# ---- QR Decomposition: Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/02-QRDecomposition.mp4', VIDEOS_WIDTH))

In [4]:
# ---- QR Decomposition ----
A = np.matrix([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
Q, R = scipy.linalg.qr(A)
Q_dot_R = Q @ R

print(f'- A: {A}')
print('---')
print(f'- Q * R: {Q_dot_R}')
print('---')
print(f'- Are A and Q * R equal? {np.allclose(A, Q_dot_R)}')

- A: [[1 2 3]
 [3 2 1]
 [2 3 1]]
---
- Q * R: [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]
---
- Are A and Q * R equal? True


---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).