<center>    
    <h1 id='matrix-decomposition-notebook-2' style='color:#7159c1; font-size:350%'>QR Decomposition</h1>
    <i style='font-size:125%'>Breaking Matrices into Blocks</i>
</center>

> **Topics**

```
- 🛡️ QR Decomposition
```

In [1]:
# ---- Imports ----
import numpy as np
import scipy
from IPython.display import HTML

# ---- Constants ----
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-qr-decomposition' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🛡️ | QR Decomposition</h1>

`QR Decomposition` decomposes any matrix $\mathbf{A}$ into two ones: $\mathbf{Q}$ and $\mathbf{R}$:

$$
\mathbf{A} = \mathbf{Q} \cdot \mathbf{R}
$$

where:

- **$\mathbf{A}$** - `Any Matrix`;

- **$\mathbf{Q}$** - `Orthonormal Matrix`;

- **$\mathbf{R}$ (AKA $\mathbf{U}$)** - `Upper Triangular Matrix`.

In order to explain this decomposition step-by-step, let's go to a hands-on exercise!!

Consider the matrix $\mathbf{A}$:

$$
\mathbf{A} = \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 2 & 1 \\
    2 & 3 & 1
\end{bmatrix}
$$

---

**- Step 1) Calculate the first column of $\mathbf{Q}$ ($\vec{q1}$):**

1.0) We first extract the first column of matrix $\mathbf{A}$:

$$
\vec{a1} = \begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix}
$$

1.1) Calculate the normalized value of the column:

$$
||\vec{a1}|| = \sqrt{1^2 + 3^2 + 2^2} = \sqrt{14}
$$

1.2) Normalize the whole column to get $\vec{q1}$:

$$
\vec{q1} = \frac{\vec{a1}}{||\vec{a1}||} = \begin{bmatrix}
    \frac{1}{\sqrt{14}} \\
    \frac{3}{\sqrt{14}} \\
    \frac{2}{\sqrt{14}}
\end{bmatrix} \approx
\begin{bmatrix}0.267 \\ 0.801 \\ 0.534\end{bmatrix}
$$

---

**- Step 2) Calculate the second column of $\mathbf{Q}$ ($\vec{q2}$):**

2.0) We first extract the second column of matrix $\mathbf{A}$:

$$
\vec{a2} = \begin{bmatrix} 2 \\ 2 \\ 3 \end{bmatrix}
$$

2.1) Calculate the projection of $\vec{a2}$ onto $\vec{q1}$:

$$
\text{proj}_\vec{q1}\vec{a2} = (\vec{q1}^T \cdot \vec{a2}) \cdot \vec{q1}
$$

2.1.0) Calculate $(\vec{q1}^T \cdot \vec{a2})$ first:

$$
(\vec{q1}^T \cdot \vec{a2}) =
(0.267 \cdot 2) + (0.801 \cdot 2) + (0.534 \cdot 3) =
3.741
$$

2.1.1) Calculate the projection:

$$
\text{proj}_\vec{q1}\vec{a2} =
(\vec{q1}^T \cdot \vec{a2}) \cdot \vec{q1} =
3.741 \cdot \begin{bmatrix} 0.267 \\ 0.801 \\ 0.534 \end{bmatrix} =
\begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix}
$$

2.2) Calculate the vector $\vec{u2}$:

$$
\vec{u2} = \vec{a2} - \text{proj}_\vec{q1}\vec{a2} =
\begin{bmatrix} 2 \\ 2 \\ 3 \end{bmatrix} -
\begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix} =
\begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix}
$$

2.3) Calculate the normalized value of $\vec{u2}$:

$$
||\vec{u2}|| = \sqrt{1^2 + (-1^2) + 1^2} = \sqrt(3)
$$

2.4) Normalize the whole column to get $\vec{q2}$:

$$
\vec{q2} = \frac{\vec{u2}}{||\vec{u2}||} =
\begin{bmatrix}
    \frac{1}{\sqrt{3}} \\
    \frac{-1}{\sqrt{3}} \\
    \frac{1}{\sqrt{3}}
\end{bmatrix} \approx
\begin{bmatrix} 0.577 \\ -0.577 \\ 0.577 \end{bmatrix}
$$

---

**- Step 3) Calculate the third column of $\mathbf{Q}$ ($\vec{q3}$):**

3.0) We first extract the third column of matrix $\mathbf{A}$:

$$
\vec{a3} = \begin{bmatrix} 3 \\ 1 \\ 1 \end{bmatrix}
$$

3.1) Calculate the projection of $\vec{a3}$ on to $\vec{q1}$:

$$
\text{proj}_\vec{q1} \vec{a3} = (\vec{q1}^T \cdot \vec{a3}) \cdot \vec{q1}
$$

3.1.0) Calculate $(\vec{q1}^T \cdot \vec{a3})$ first:

$$
\vec{q1}^T \cdot \vec{a3} =
(0.267 \cdot 3) + (0.801 \cdot 1) + (0.534 \cdot 1) =
2.138
$$

3.1.1) Calculate the projection:

$$
\text{proj}_\vec{q1} \vec{a3} =
2.138 \cdot \begin{bmatrix} 0.267 \\ 0.801 \\ 0.534 \end{bmatrix} =
\begin{bmatrix} 0.571 \\ 1.714 \\ 1.143 \end{bmatrix}
$$

3.2) Calculate the projection of $\vec{a3}$ on to $\vec{q2}$:

$$
\text{proj}_\vec{q2} \vec{a3} = (\vec{q2}^T \cdot \vec{a3}) \cdot \vec{q2}
$$

3.2.0) Calculate $(\vec{q2}^T \cdot \vec{a3})$ first:

$$
\vec{q1}^T \cdot \vec{a3} =
(0.577 \cdot 3) + (-0.577 \cdot 1) + (0.577 \cdot 1) =
1.732
$$

3.2.1) Calculate the projection:

$$
\text{proj}_\vec{q2} \vec{a3} =
1.732 \cdot \begin{bmatrix} 0.577 \\ -0.577 \\ 0.577 \end{bmatrix} =
\begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix}
$$

3.3) Calculate the vector $\vec{u3}$:

$$
\vec{u3} = \vec{a3} - \text{proj}_\vec{q1} \vec{a3} - \text{proj}_\vec{q2} \vec{a3} =
\begin{bmatrix} 3 \\ 1 \\ 1 \end{bmatrix} -
\begin{bmatrix} 0.571 \\ 1.714 \\ 1.143 \end{bmatrix} -
\begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix} =
\begin{bmatrix} 1.429 \\ 0.286 \\ -1.143 \end{bmatrix}
$$


3.4) Calculate the normalized value of $\vec{u3}$:

$$
||\vec{u3}|| = \sqrt{1.429^2 + 0.286^2 + (-1.143)^2)} = \sqrt{3.4303}
$$

3.5) Normalize the whole column to get $\vec{q3}$:

$$
\vec{q3} = \frac{\vec{u3}}{||\vec{u3}||} =
\begin{bmatrix}
    \frac{1.429}{\sqrt{3.4303}} \\
    \frac{0.286}{\sqrt{3.4303}} \\
    \frac{-1.143}{\sqrt{3.4303}}
\end{bmatrix} =
\begin{bmatrix} 0.771 \\ 0.154 \\ -0.617 \end{bmatrix}
$$

---

**- Step 4) Create matrix $\mathbf{Q}$ with $\vec{q1}$, $\vec{q2}$ and $\vec{q3}$ as its columns:**

$$
\mathbf{Q} =
\begin{bmatrix} \vec{q1} \\ \vec{q2} \\ \vec{q3} \end{bmatrix} =
\begin{bmatrix}
    0.267 & o.577 & 0.771 \\
    0.801 & -0.577 & 0.154 \\
    0.534 & 0.577 & -0.617
\end{bmatrix}
$$

---

**- Step 5) Create matrix $\mathbf{R}$ by multiplying $\mathbf{Q}^T$ by $\mathbf{A}$:**

$$
\mathbf{R} = \mathbf{Q}^T \cdot \mathbf{A} =
\begin{bmatrix}
    3.742 & 3.742 & 2.138 \\
    0 & 1.732 & 1.732 \\
    0 & 0 & 1.852
\end{bmatrix}
$$

---

And done!! Our matrix $\mathbf{A}$ has just been decomposed into a `Orthogonal Matrix` ($\mathbf{Q}$) and an `Upper Triangular Matrix` ($\mathbf{R}$):

$$
\begin{array}
    \mathbf{A} = \mathbf{Q} \cdot \mathbf{R} \\ \\
    \big\downarrow \\ \\
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 2 & 1 \\
        2 & 3 & 1
    \end{bmatrix} =
    \begin{bmatrix}
        0.267 & o.577 & 0.771 \\
        0.801 & -0.577 & 0.154 \\
        0.534 & 0.577 & -0.617
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        3.742 & 3.742 & 2.138 \\
        0 & 1.732 & 1.732 \\
        0 & 0 & 1.852
    \end{bmatrix}
\end{array}
$$

In [2]:
# ---- QR Decomposition: Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/02-QRDecomposition.mp4', VIDEOS_WIDTH))

In [3]:
# ---- QR Decomposition ----
A = np.matrix([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
Q, R = scipy.linalg.qr(A)
Q_dot_R = Q @ R

print(f'- A: {A}')
print('---')
print(f'- Q * R: {Q_dot_R}')
print('---')
print(f'- Are A and Q * R equal? {np.allclose(A, Q_dot_R)}')

- A: [[1 2 3]
 [3 2 1]
 [2 3 1]]
---
- Q * R: [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]
---
- Are A and Q * R equal? True


---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).