<center>    
    <h1 id='matrix-decomposition-notebook-4' style='color:#7159c1; font-size:350%'>Singular Value Decomposition</h1>
    <i style='font-size:125%'>Breaking Matrices into Blocks</i>
</center>

> **Topics**

```
- 🛡️ Singular Value Decomposition
```

In [1]:
# ---- Imports ----
import numpy as np
import scipy
from IPython.display import HTML

# ---- Constants ----
VIDEOS_WIDTH = (600)
VIDEOS_PATH = ('./videos')

# ---- Functions ----
def generateVideoEmbed(path, width):
    """
    Generates a string containing a centered video tag with a specific width and video source.

    - Input:
        / path: string;
        / width: float.

    - Output:
        / video_tag: string.
    """
    video_tag = f'<center><video width="{width}" autoplay controls loop><source src="{path}" type="video/mp4" />Your browser does not support the video tag 😢</video></center>'
    return video_tag

<h1 id='0-singular-value-decomposition' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>🛡️ | Singular Value Decomposition</h1>

`Singular Value Decomposition`, AKA `SVD`, decomposes any matrix $\mathbf{A}$ into three ones: $\mathbf{U}$, $\Sigma$ and $\mathbf{V}^T$:

$$
\mathbf{A} = \mathbf{U} \cdot \Sigma \cdot \mathbf{V}^T
$$

where:

- **$\mathbf{A}$** - `Any Matrix`;

- **$\mathbf{U}$** - `Orthogonal Matrix`;

- **$\Sigma$** - `Rectangular, Diagonal Matrix`;

- **$\mathbf{V}^T$** - `Orthogonal Matrix`.


In order to explain this decomposition step-by-step, let's go to a hands-on exercise!!

Consider the matrix $\mathbf{A}$:

$$
\mathbf{A} = \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 2 & 1 \\
    2 & 3 & 1
\end{bmatrix}
$$

---

**- Step 1) Calculate the $\mathbf{A}^T$ and then $\mathbf{A} \cdot \mathbf{A}^T$ to get the `Simmetric Left Matrix` ($\mathbf{SL}$) and then $\mathbf{A}^T \cdot \mathbf{A}$ to get the `Simmetric Right Matrix` ($\mathbf{SR}$):**

$$
\begin{array}
    \mathbf{A}^T = \begin{bmatrix} 1 & 3 & 2 \\ 2 & 2 & 3 \\ 3 & 1 & 1 \end{bmatrix} \\ \\
    \mathbf{SL} = \mathbf{A} \cdot \mathbf{A}^T = \begin{bmatrix} 14 & 10 & 11 \\ 10 & 14 & 13 \\ 11 & 13 & 14 \end{bmatrix} \\ \\
    \mathbf{SR} = \mathbf{A}^T \cdot \mathbf{A} = \begin{bmatrix} 14 & 14 & 8 \\ 14 & 17 & 11 \\ 8 & 11 & 11 \end{bmatrix}
\end{array}
$$

---

**- Step 2) Calculate the Eigenvectors, Eigenvalues and Singular Values of $\mathbf{SL}$ and $\mathbf{SR}$:**

In SVD, the Eigenvectors of $\mathbf{SL}$ and $\mathbf{SR}$ are called `Singular Vectors`!! After calculating the Eigenvalues, we must sort them in descending order and, consequently, sort the Eigenvectors accordingly to the rearrangements applied to teh Eigenvalues. For instance, if the first and second Eigenvalues of $\mathbf{SR}$ have gotten swapped, we must do the same to the Eigenvectors of $\mathbf{SR}$.

Also, the Eigenvalues ($\lambda$) of $\mathbf{SL}$ and $\mathbf{SR}$ are the same, so the first Eigenvalue of $\mathbf{SL}$ is equals to the first Eigenvalue of $\mathbf{SR}$, the second is equals to the second and so on...

After calculating the Eigenvalues, we can get the `Singular Values` by square rooting each Eigenvalue:

$$
\begin{array}
    \text{Singular Values:} \\ \\
    \sigma_1 = \sqrt{\lambda_1} \\ \\
    \sigma_2 = \sqrt{\lambda_2} \\ \\
    \sigma_3 = \sqrt{\lambda_3}
\end{array}
$$

---

**- Step 3) Create the matrices $\mathbf{U}$, $\Sigma$ and $\mathbf{V}^T$:**

$\mathbf{U}$ consists of a matrix containing the Singular Vectors of $\mathbf{SL}$ as the columns; $\Sigma$ consists of a diagonal matrix containing the Singular Values as the diagonal values; and $\mathbf{V}^T$ consists of a transposed matrix containing the Singular Vectors of $\mathbf{SR}$ as the rows. Then:

$$
\begin{array}
    \mathbf{U} = \begin{bmatrix}
           |         &    |     &    |    \\
        \vec{u1}     & \vec{u2} & \vec{u3} \\
        |         &    |     &    |
    \end{bmatrix}
    \\ \\
    \Sigma = \begin{bmatrix}
        \sigma_1 &    0     &    0     \\
            0    & \sigma_2 &    0     \\
            0    &    0     & \sigma_3
    \end{bmatrix}
    \\ \\
    \mathbf{V}^T = \begin{bmatrix}
        - & \vec{v1} & - \\
        - & \vec{v2} & - \\
        - & \vec{v3} & - \\
    \end{bmatrix}
\end{array}
$$

---

And done!! Our matrix $\mathbf{A}$ has just been decomposed into a `Orthogonal Matrix` ($\mathbf{U}$), a `Rectangular, Diagonal Matrix` ($\Sigma$) and a `Orthogonal Matrix` ($\mathbf{V}^T$):

$$
\begin{array}
    \mathbf{A} = \mathbf{U} \cdot \Sigma \cdot \mathbf{V}^T \\ \\
    \big\downarrow \\ \\
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 2 & 1 \\
        2 & 3 & 1
    \end{bmatrix} =
    \begin{bmatrix}
           |         &    |     &    |    \\
        \vec{u1}     & \vec{u2} & \vec{u3} \\
        |         &    |     &    |
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        \sigma_1 &    0     &    0     \\
            0    & \sigma_2 &    0     \\
            0    &    0     & \sigma_3
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        - & \vec{v1} & - \\
        - & \vec{v2} & - \\
        - & \vec{v3} & - \\
    \end{bmatrix}
\end{array}
$$

In [3]:
# ---- Singular Value Decomposition: Visualization ----
HTML(generateVideoEmbed(f'{VIDEOS_PATH}/04-SVDDecomposition.mp4', VIDEOS_WIDTH))

In [9]:
# ---- Singular Value Decomposition ----
A = np.matrix([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
U, SIGMA, VT = scipy.linalg.svd(A)
SIGMA = np.diag(SIGMA)
U_dot_SIGMA_dot_VT = U @ SIGMA @ VT

print(f'- A: {A}')
print('---')
print(f'- U * Σ * VT: {U_dot_SIGMA_dot_VT}')
print('---')
print(f'- Are A and U * Σ * VT Equal? {np.allclose(A, U_dot_SIGMA_dot_VT)}')

- A: [[1 2 3]
 [3 2 1]
 [2 3 1]]
---
- U * Σ * VT: [[1. 2. 3.]
 [3. 2. 1.]
 [2. 3. 1.]]
---
- Are A and U * Σ * VT Equal? True


---

<h1 id='reach-me' style='color:#7159c1; border-bottom:3px solid #7159c1; letter-spacing:2px; font-family:JetBrains Mono; font-weight: bold; text-align:left; font-size:240%;padding:0'>📫 | Reach Me</h1>

> **Email** - [csfelix08@gmail.com](mailto:csfelix08@gmail.com?)

> **Linkedin** - [linkedin.com/in/csfelix/](https://www.linkedin.com/in/csfelix/)

> **GitHub:** - [CSFelix](https://github.com/CSFelix)

> **Kaggle** - [DSFelix](https://www.kaggle.com/dsfelix)

> **Portfolio** - [CSFelix.io](https://csfelix.github.io/).